export type cardData = {
  name:string
  description:string
  image?:string
  imagePosition?:string
  base?:string
}

export const ingredients = [
  { name: "特浓咖啡",
    description: "作为制作各种咖啡的标准单位, 一份浓缩咖啡只有30克液体, 但要加6-8克细磨咖啡粉",
  },
  { name: "牛奶",
    description: "包括热牛奶和奶泡, 奶泡是添加了空气的牛奶. 这种充气过程会产生气泡或泡沫，并有助于牛奶达到奶油般的稠度.",
  },
  { name: "水",
    description: "",
  },
  { name: "巧克力",
    description: "",
  },
  { name: "奶油",
    description: "",
  },
]
export const coffees: cardData[] = [
  { name: "意式浓缩咖啡",
    description:"最简单的意式咖啡, 拥有浓郁的口感.",
    base: "一份浓缩咖啡",
    image: "/Coffee-Types-Comparison-Chart.jpg",
    imagePosition: "-50px -150px",
  },
  { name: "拿铁咖啡",
    description: "拿铁是最为国人熟悉的意式咖啡品项. 牛奶的温润调味, 让原本甘苦的咖啡变得柔滑香甜.",
    base: "三分之一的浓缩咖啡、三分之二的热牛奶和奶泡",
    image: "/Coffee-Types-Comparison-Chart.jpg",
    imagePosition: "-500px -340px"
  },
  { name: "卡布奇诺",
    description: "卡布奇诺和拿铁咖啡构成基本一致. 他们的区别是卡布奇诺的奶泡比牛奶多, 而拿铁则刚好相反. 卡布奇诺中特浓咖啡的浓郁口味, 配以润滑的奶泡, 颇有一些汲精敛露的意味.",
    base: "三分之一的浓缩咖啡、三分之一的热牛奶和三分之一的奶泡",
    image: "/Coffee-Types-Comparison-Chart.jpg",
    imagePosition: "-50px -340px",
  },
  { name: "美式咖啡",
    description: "美式咖啡源自于战争时期在欧洲的美军将热水混进欧洲常见的小份浓缩咖啡的习惯. 因为一般说来，美国人对咖啡的制作较为随意且简单，这种方法便很快地随着美国连锁店在世界上的普及而流行开来.",
    base: "一份或两份浓缩咖啡加热水",
    image: "/Coffee-Types-Comparison-Chart.jpg",
    imagePosition: "-280px -340px",
  },
  { name: "玛奇朵",
    description: "玛奇朵的意思是 \"标记, 烙印\". 因此玛奇朵咖啡的字面意思是以牛奶来上色的浓缩咖啡.",
    base: "少量奶泡和一份浓缩咖啡",
    image: "/Coffee-Types-Comparison-Chart.jpg",
    imagePosition: "-50px -250px",
  },
  { name: "摩卡",
    description: "摩卡咖啡是一种甜咖啡饮料, 是一种最古老的咖啡，其历史要追溯到咖啡的起源. 摩卡得名于有名的摩卡港.",
    base: "浓缩咖啡, 牛奶, 巧克力, 鲜奶油混合",
    image: "/Coffee-Types-Comparison-Chart.jpg",
    imagePosition: "-280px -450px",
  },
]
export const secondaries = [
  { name: "糖",
    description: "",
  },
  { name: "肉桂",
    description: "肉桂可以给你华丽的温暖味道. 而且可以控制血糖并提高胆固醇水平.",
  },
  { name: "姜",
    description: "添加生姜特有的辛辣风味. 生姜作为药用植物历史悠久，从感冒到癌症都应有尽有，现代研究的重点是其抗氧化剂，抗炎和抗癌特性.",
  },
  { name: "柠檬",
    description: "可以消除苦味并提升咖啡的风味. 柠檬和酸橙含有丰富的维生素和抗氧化剂，因此将它们添加到咖啡中可以帮助抵抗癌症并增强免疫系统.",
  },
  { name: "蜂蜜",
    description: "喜欢甜咖啡的不错选择, 它比精制糖提供更多的营养，包括抗氧化剂、矿物质和维生素，还可以舒缓喉咙.",
  },
]